<?php
include 'db.php';
require_once('tcpdf/tcpdf.php');

// PDF Generation
if (isset($_GET['generate_pdf']) && isset($_GET['event_id'])) {
    $eventId = (int)$_GET['event_id'];
    $stmt = $conn->prepare("SELECT * FROM event_applications WHERE id = ?");
    $stmt->bind_param("i", $eventId);
    $stmt->execute();
    $event = $stmt->get_result()->fetch_assoc();
    $stmt->close();

    if ($event) {
        class MYPDF extends TCPDF {
            public function Header() {
                $this->SetFont('helvetica', 'B', 14);
                $this->Cell(0, 10, 'Event Report', 0, 1, 'C');
            }
            public function Footer() {
                $this->SetY(-15);
                $this->SetFont('helvetica', 'I', 8);
                $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 0, 'C');
            }
        }

        $pdf = new MYPDF();
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Event Admin');
        $pdf->SetTitle($event['title']);
        $pdf->SetMargins(20, 30, 20);
        $pdf->AddPage();

        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 10, $event['title'], 0, 1, 'L');
        $pdf->Ln(2);
        $pdf->SetFont('helvetica', '', 12);
        $pdf->MultiCell(0, 10, "Organizer Email: " . $event['organizer_email'], 0, 'L');
        $pdf->Ln(3);
        $pdf->SetFont('helvetica', 'B', 13);
        $pdf->Cell(0, 10, 'Description:', 0, 1, 'L');
        $pdf->SetFont('helvetica', '', 12);
        $pdf->MultiCell(0, 10, $event['description'] ?: 'No description provided.', 0, 'L');

        $pdf->Ln(5);
        $pdf->SetFont('helvetica', 'B', 13);
        $pdf->Cell(0, 10, 'Event Flyers:', 0, 1, 'L');
        $pdf->Ln(2);

        $maxWidth = 55; $spacing = 5;
        $x = $pdf->GetX(); $y = $pdf->GetY(); $startX = $x; $imgCount = 0;
        foreach (['image1', 'image2', 'image3'] as $imgKey) {
            if (!empty($event[$imgKey]) && file_exists($event[$imgKey])) {
                list($origW, $origH) = getimagesize($event[$imgKey]);
                $aspect = $origH / $origW;
                $newHeight = $maxWidth * $aspect;
                $pdf->Image($event[$imgKey], $x, $y, $maxWidth, $newHeight, '', '', '', true, 300, '', false, false, 0, 'LT', false, false);
                $x += $maxWidth + $spacing;
                $imgCount++;
                if ($imgCount % 3 == 0) {
                    $x = $startX;
                    $y += $newHeight + $spacing;
                }
            }
        }

        $maxImgHeight = 0;
        $imagePaths = array_filter([$event['image1'], $event['image2'], $event['image3']], fn($img) => !empty($img) && file_exists($img));
        $imagesInLastRow = count($imagePaths) % 3;
        if ($imagesInLastRow == 0 && count($imagePaths) > 0) $imagesInLastRow = 3;
        if ($imagesInLastRow > 0) {
            $lastImages = array_slice($imagePaths, -$imagesInLastRow);
            foreach ($lastImages as $img) {
                list($w, $h) = getimagesize($img);
                $aspect = $h / $w;
                $height = $maxWidth * $aspect;
                if ($height > $maxImgHeight) $maxImgHeight = $height;
            }
        }

        $pdf->SetY($y + $maxImgHeight + 10);
        $pdf->SetFont('helvetica', 'I', 11);
        $pdf->MultiCell(0, 10, "This PDF report was automatically generated by the admin system.", 0, 'L');
        $pdf->Ln(5);
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 10, "Report Generated Date: " . date('Y-m-d H:i:s'), 0, 1, 'L');
        $pdf->Output('event_report_' . $eventId . '.pdf', 'I');
        exit;
    } else {
        echo "Event not found.";
        exit;
    }
}

// Fetch past events (with search)
$today = date('Y-m-d');
$searchTerm = $_GET['search'] ?? '';
$searchTermLike = "%" . $searchTerm . "%";

if (!empty($searchTerm)) {
    $stmt = $conn->prepare("SELECT ea.*, u.username FROM event_applications ea LEFT JOIN users u ON ea.organizer_email = u.email WHERE ea.date < ? AND (ea.title LIKE ? OR ea.organizer_email LIKE ?)");
    $stmt->bind_param("sss", $today, $searchTermLike, $searchTermLike);
} else {
    $stmt = $conn->prepare("SELECT ea.*, u.username FROM event_applications ea LEFT JOIN users u ON ea.organizer_email = u.email WHERE ea.date < ?");
    $stmt->bind_param("s", $today);
}
$stmt->execute();
$events = $stmt->get_result();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Past Event Reports</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary-bg: #F9FAFB;
            --card-bg: #FFFFFF;
            --text-color: #374151;
            --heading-color: #111827;
            --accent-color: #1E3A8A; /* Dark Blue */
            --accent-hover: #172B68;
            --border-color: #E5E7EB;
            --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
            --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
        }
        
        body {
            font-family: 'Inter', sans-serif;
            background: var(--primary-bg);
            color: var(--text-color);
            line-height: 1.6;
        }

        .container {
            max-width: 1100px;
            margin: 4rem auto;
            padding: 2rem;
        }

        .header {
            text-align: center;
            margin-bottom: 2.5rem;
        }

        .header h2 {
            font-weight: 700;
            color: var(--heading-color);
            font-size: 2.5rem;
        }

        .header p {
            color: #6B7280;
            margin-top: 0.5rem;
        }

        .card {
            background: var(--card-bg);
            border-radius: 12px;
            box-shadow: var(--shadow-md);
            padding: 2rem;
            margin-bottom: 2rem;
            border: 1px solid var(--border-color);
        }
        
        .search-form {
            display: flex;
            gap: 1rem;
            align-items: center;
        }

        .search-form .form-control {
            border-radius: 8px;
            border: 1px solid var(--border-color);
            padding: 0.75rem 1rem;
            flex: 1;
            transition: border-color 0.2s, box-shadow 0.2s;
        }

        .search-form .form-control:focus {
            outline: none;
            border-color: var(--accent-color);
            box-shadow: 0 0 0 3px rgba(30, 58, 138, 0.2); /* Dark blue focus shadow */
        }
        
        .btn-primary {
            background-color: var(--accent-color);
            border-color: var(--accent-color);
            border-radius: 8px;
            font-weight: 600;
            padding: 0.75rem 1.5rem;
            transition: background-color 0.2s ease-in-out, transform 0.1s ease-in-out;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }
        
        .btn-primary:hover {
            background-color: var(--accent-hover);
            border-color: var(--accent-hover);
            transform: translateY(-1px);
        }
        
        .table-responsive {
            margin-top: 2rem;
        }

        .table-container {
            background: var(--card-bg);
            border-radius: 12px;
            overflow: hidden;
            box-shadow: var(--shadow-md);
            border: 1px solid var(--border-color);
        }
        
        .table {
            margin-bottom: 0;
        }
        
        .table thead th {
            background-color: #F3F4F6;
            color: var(--heading-color);
            font-weight: 600;
            padding: 1rem;
            border-bottom: 1px solid var(--border-color);
        }
        
        .table tbody tr {
            transition: background-color 0.2s;
        }
        
        .table tbody tr:hover {
            background-color: #F9FAFB;
        }
        
        .table td, .table th {
            border-color: var(--border-color);
            vertical-align: middle;
            padding: 1.2rem 1rem;
        }
        
        .btn-download {
            display: inline-flex;
            align-items: center;
            gap: 0.5rem;
            font-size: 0.9rem;
            font-weight: 500;
            text-decoration: none;
            color: var(--card-bg);
            background-color: var(--accent-color);
            padding: 0.5rem 1rem;
            border-radius: 8px;
            transition: background-color 0.2s, transform 0.1s;
        }
        
        .btn-download:hover {
            background-color: var(--accent-hover);
            transform: translateY(-1px);
        }
        
        .text-muted {
            color: #6B7280 !important;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="header">
        <h2>Past Event Reports</h2>
        <p>Manage and download reports for all past events. Use the search bar to quickly find an event.</p>
    </div>

    <div class="card">
        <form method="get" class="search-form">
            <input type="text" name="search" value="<?= htmlspecialchars($searchTerm) ?>" class="form-control" placeholder="Search by event title or organizer email">
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-search"></i> Search
            </button>
        </form>
    </div>

    <div class="table-container">
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Organizer</th>
                        <th>Email</th>
                        <th>Date</th>
                        <th>PDF Report</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($events->num_rows > 0): ?>
                        <?php while ($e = $events->fetch_assoc()): ?>
                            <tr>
                                <td><?= $e['id'] ?></td>
                                <td><?= htmlspecialchars($e['title']) ?></td>
                                <td><?= htmlspecialchars($e['username'] ?? '-') ?></td>
                                <td><?= htmlspecialchars($e['organizer_email']) ?></td>
                                <td><?= htmlspecialchars($e['date']) ?></td>
                                <td>
                                    <a href="?generate_pdf=1&event_id=<?= $e['id'] ?>" class="btn-download" target="_blank">
                                        <i class="bi bi-file-earmark-arrow-down"></i> Download PDF
                                    </a>
                                </td>
                            </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" class="text-center text-muted">No events found.</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>

<?php
$stmt->close();
$conn->close();
?>