<?php
include 'db.php';
require_once('tcpdf/tcpdf.php');

// PDF Generation
if (isset($_GET['generate_pdf']) && isset($_GET['event_id'])) {
    $eventId = (int)$_GET['event_id'];
    $stmt = $conn->prepare("SELECT * FROM event_applications WHERE id = ?");
    $stmt->bind_param("i", $eventId);
    $stmt->execute();
    $event = $stmt->get_result()->fetch_assoc();
    $stmt->close();

    if ($event) {
        class MYPDF extends TCPDF {
            public function Header() {
                $this->SetFont('helvetica', 'B', 14);
                $this->Cell(0, 10, 'Event Report', 0, 1, 'C');
            }
            public function Footer() {
                $this->SetY(-15);
                $this->SetFont('helvetica', 'I', 8);
                $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 0, 'C');
            }
        }

        $pdf = new MYPDF();
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Event Admin');
        $pdf->SetTitle($event['title']);
        $pdf->SetMargins(20, 30, 20);
        $pdf->AddPage();

        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 10, $event['title'], 0, 1, 'L');
        $pdf->Ln(2);
        $pdf->SetFont('helvetica', '', 12);
        $pdf->MultiCell(0, 10, "Organizer Email: " . $event['organizer_email'], 0, 'L');
        $pdf->Ln(3);
        $pdf->SetFont('helvetica', 'B', 13);
        $pdf->Cell(0, 10, 'Description:', 0, 1, 'L');
        $pdf->SetFont('helvetica', '', 12);
        $pdf->MultiCell(0, 10, $event['description'] ?: 'No description provided.', 0, 'L');

        $pdf->Ln(5);
        $pdf->SetFont('helvetica', 'B', 13);
        $pdf->Cell(0, 10, 'Event Flyers:', 0, 1, 'L');
        $pdf->Ln(2);

        $maxWidth = 55; $spacing = 5;
        $x = $pdf->GetX(); $y = $pdf->GetY(); $startX = $x; $imgCount = 0;
        foreach (['image1', 'image2', 'image3'] as $imgKey) {
            if (!empty($event[$imgKey]) && file_exists($event[$imgKey])) {
                list($origW, $origH) = getimagesize($event[$imgKey]);
                $aspect = $origH / $origW;
                $newHeight = $maxWidth * $aspect;
                $pdf->Image($event[$imgKey], $x, $y, $maxWidth, $newHeight, '', '', '', true, 300, '', false, false, 0, 'LT', false, false);
                $x += $maxWidth + $spacing;
                $imgCount++;
                if ($imgCount % 3 == 0) {
                    $x = $startX;
                    $y += $newHeight + $spacing;
                }
            }
        }

        $maxImgHeight = 0;
        $imagePaths = array_filter([$event['image1'], $event['image2'], $event['image3']], fn($img) => !empty($img) && file_exists($img));
        $imagesInLastRow = count($imagePaths) % 3;
        if ($imagesInLastRow == 0 && count($imagePaths) > 0) $imagesInLastRow = 3;
        if ($imagesInLastRow > 0) {
            $lastImages = array_slice($imagePaths, -$imagesInLastRow);
            foreach ($lastImages as $img) {
                list($w, $h) = getimagesize($img);
                $aspect = $h / $w;
                $height = $maxWidth * $aspect;
                if ($height > $maxImgHeight) $maxImgHeight = $height;
            }
        }

        $pdf->SetY($y + $maxImgHeight + 10);
        $pdf->SetFont('helvetica', 'I', 11);
        $pdf->MultiCell(0, 10, "This PDF report was automatically generated by the admin system.", 0, 'L');
        $pdf->Ln(5);
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 10, "Report Generated Date: " . date('Y-m-d H:i:s'), 0, 1, 'L');
        $pdf->Output('event_report_' . $eventId . '.pdf', 'I');
        exit;
    } else {
        echo "Event not found.";
        exit;
    }
}

// Fetch past events (with search)
$today = date('Y-m-d');
$searchTerm = $_GET['search'] ?? '';
$searchTermLike = "%" . $searchTerm . "%";

if (!empty($searchTerm)) {
    $stmt = $conn->prepare("SELECT ea.*, u.username FROM event_applications ea LEFT JOIN users u ON ea.organizer_email = u.email WHERE ea.date < ? AND (ea.title LIKE ? OR ea.organizer_email LIKE ?)");
    $stmt->bind_param("sss", $today, $searchTermLike, $searchTermLike);
} else {
    $stmt = $conn->prepare("SELECT ea.*, u.username FROM event_applications ea LEFT JOIN users u ON ea.organizer_email = u.email WHERE ea.date < ?");
    $stmt->bind_param("s", $today);
}
$stmt->execute();
$events = $stmt->get_result();
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Past Event Reports</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
<div class="container mt-5">
  <h2 class="mb-4 text-center">Past Event Reports</h2>

  <form method="get" class="mb-4">
    <div class="input-group">
      <input type="text" name="search" value="<?= htmlspecialchars($searchTerm) ?>" class="form-control" placeholder="Search by event title or organizer email">
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  </form>

  <div class="table-responsive">
    <table class="table table-bordered align-middle">
      <thead class="table-dark">
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Organizer</th>
          <th>Email</th>
          <th>Date</th>
          <th>PDF Report</th>
        </tr>
      </thead>
      <tbody>
        <?php if ($events->num_rows > 0): ?>
          <?php while ($e = $events->fetch_assoc()): ?>
            <tr>
              <td><?= $e['id'] ?></td>
              <td><?= htmlspecialchars($e['title']) ?></td>
              <td><?= htmlspecialchars($e['username'] ?? '-') ?></td>
              <td><?= htmlspecialchars($e['organizer_email']) ?></td>
              <td><?= htmlspecialchars($e['date']) ?></td>
              <td>
                <a href="?generate_pdf=1&event_id=<?= $e['id'] ?>" class="btn btn-sm btn-primary" target="_blank">Download PDF</a>
              </td>
            </tr>
          <?php endwhile; ?>
        <?php else: ?>
          <tr>
            <td colspan="6" class="text-center text-muted">No events found.</td>
          </tr>
        <?php endif; ?>
      </tbody>
    </table>
  </div>
</div>
</body>
</html>

<?php
$stmt->close();
$conn->close();
?>
